apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cloudtribe-org-tls
spec:
  secretName: cloudtribe-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cloudtribe.org
  dnsNames:
    - cloudtribe.org
    - www.cloudtribe.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - cloudtribe.org
          - www.cloudtribe.org